function Fmekf = calcFmekf_auto(px_hat,py_hat,pz_hat,u_hat,v_hat,w_hat,qw_hat,qx_hat,qy_hat,qz_hat,wx_hat,wy_hat,wz_hat,Fa_x,Fa_y,Fa_z,Ft_x,Ft_y,Ft_z,Fr_x,Fr_y,Fr_z,Fn_x,Fn_y,Fn_z,m,g,Ma_x,Ma_y,Ma_z,Mr_x,Mr_y,Mr_z,Mn_x,Mn_y,Mn_z,Cpx,Jx,Jy,Jz,dt)
%calcFmekf_auto
%    Fmekf = calcFmekf_auto(PX_HAT,PY_HAT,PZ_HAT,U_HAT,V_HAT,W_HAT,QW_HAT,QX_HAT,QY_HAT,QZ_HAT,WX_HAT,WY_HAT,WZ_HAT,Fa_x,Fa_y,Fa_z,Ft_x,Ft_y,Ft_z,Fr_x,Fr_y,Fr_z,Fn_x,Fn_y,Fn_z,M,G,Ma_x,Ma_y,Ma_z,Mr_x,Mr_y,Mr_z,Mn_x,Mn_y,Mn_z,Cpx,Jx,Jy,Jz,DT)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2025-01-04 23:10:26

t2 = dt.*u_hat;
t3 = dt.*v_hat;
t4 = dt.*w_hat;
t5 = dt.*wx_hat;
t6 = dt.*wy_hat;
t7 = dt.*wz_hat;
t8 = qw_hat.^2;
t9 = qx_hat.^2;
t10 = qy_hat.^2;
t11 = qz_hat.^2;
t12 = -Jy;
t13 = -Jz;
t14 = 1.0./Jx;
t15 = 1.0./Jy;
t16 = 1.0./Jz;
t17 = -t9;
t18 = -t10;
t19 = -t11;
t20 = Jx+t12;
t21 = Jx+t13;
t22 = Jy+t13;
mt1 = [1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,dt.*(t8+t9+t18+t19),dt.*(qw_hat.*qz_hat.*2.0+qx_hat.*qy_hat.*2.0),dt.*(qw_hat.*qy_hat-qx_hat.*qz_hat).*-2.0,1.0,-t7,t6,0.0,0.0,0.0,0.0,0.0,0.0,dt.*(qw_hat.*qz_hat-qx_hat.*qy_hat).*-2.0,dt.*(t8+t10+t17+t19),dt.*(qw_hat.*qx_hat.*2.0+qy_hat.*qz_hat.*2.0),t7,1.0,-t5,0.0,0.0,0.0,0.0,0.0,0.0,dt.*(qw_hat.*qy_hat.*2.0+qx_hat.*qz_hat.*2.0),dt.*(qw_hat.*qx_hat-qy_hat.*qz_hat).*-2.0,dt.*(t8+t11+t17+t18),-t6,t5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0];
mt2 = [0.0,0.0,0.0,0.0,0.0,t4,-t3,dt,0.0,0.0,1.0,-t7.*t15.*t21,t6.*t16.*t20,0.0,0.0,0.0,-t4,0.0,t2,0.0,dt,0.0,t7.*t14.*t22,1.0,t5.*t16.*t20,0.0,0.0,0.0,t3,-t2,0.0,0.0,0.0,dt,t6.*t14.*t22,-t5.*t15.*t21,1.0];
Fmekf = reshape([mt1,mt2],12,12);
end
